"""test_column_retry

Revision ID: 6f21a0f4a5fc
Revises: 278df8e96c43
Create Date: 2026-01-04 05:00:37.086580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f21a0f4a5fc'
down_revision: Union[str, Sequence[str], None] = '278df8e96c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_migration_col', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_migration_col')
    # ### end Alembic commands ###
