"""remove_test_column_cleanup

Revision ID: 78f6cf7118d5
Revises: 6f21a0f4a5fc
Create Date: 2026-01-04 05:02:26.387171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f6cf7118d5'
down_revision: Union[str, Sequence[str], None] = '6f21a0f4a5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_migration_col')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_migration_col', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
